name: chromium issue tracker feed
on:
  schedule:
    - cron:  '0 */4 * * *'
  workflow_dispatch:

jobs:
  commits_crawler:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: 22.4
        cache: 'npm'
    - run: npm ci
    - name: Execute playwright and fetch issues
      run: npm run playwright
    - run: npm run feed:issues
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    - run: |
        ls feeds/chromium_issue_tracker
        cp feeds/chromium_issue_tracker/atom.xml.new feeds/chromium_issue_tracker/atom.xml
    - uses: EndBug/add-and-commit@v9
      with:
        add: 'feeds/chromium_issue_tracker/atom.xml'
        author_name: 'github-actions[bot]'
        author_email: '41898282+github-actions[bot]@users.noreply.github.com'
